" vim600: set foldmethod=marker:

" general setup
let s:cur_rtp = &runtimepath
let s:new_rtp = "~/.dotfiles/vim/runtime," . s:cur_rtp . ",~/.dotfiles/vim/runtime/after"
let &runtimepath = s:new_rtp
if has('win32')
  set shell=bash.exe
endif

set t_Co=256

call pathogen#infect('~/.dotfiles/vim/bundle/{}')
call pathogen#helptags()

" if we're on a GUI or in a good xterm, use the mouse
set mouse=a
set ttymouse=xterm2

" supertab
let g:SuperTabDefaultCompletionType = "context"

" python
let python_highlight_all = 1

" tagbar
map <Leader>tt :TagbarToggle<CR>
let g:tagbar_autoclose = 1
let g:tagbar_autofocus = 1
let g:tagbar_left = 1

" tab complete
set wildmenu
set wildignore+=*.pyc,*.pyo

" file information
set modeline
set number
set relativenumber
set fileformats=unix,dos,mac
set backupcopy=yes
set nobackup
set writebackup

" viminfo
"   200 files marks, global marks, 50 lines per register, no hlsearch
"   10 search lines, all saved in ~/.viminfo
set viminfo='200,f1,\"50,h,/10,:0,@0,n~/.viminfo

" HTML
let g:html_exclude_tags = ['html', 'style', 'script', 'body']

" session options
set sessionoptions=curdir,folds,globals,slash,unix,tabpages


" search options
set incsearch
set hlsearch
set ignorecase
set smartcase

" editing options
set hidden
set laststatus=2
set title
set titlestring=VIM\:\ %f%m%h
set showmatch
set shiftwidth=2
set softtabstop=2
set tabstop=8
set expandtab
set autoindent
set smartindent
set cinoptions=(0,W1s
set showcmd
syntax on
set background=dark
colorscheme molokai
filetype indent on
filetype plugin on

au FileType go set noexpandtab
au FileType go set shiftwidth=4
au FileType go set softtabstop=4
au FileType go set tabstop=4

set statusline=%f%m%r%h%w%=%l,%c/%L\ %y
set statusline+=%{fugitive#statusline()}

if exists('+colorcolumn')
  set colorcolumn=80,100,120
endif

let g:lsc_server_commands = {
      \ 'python': 'pyls',
      \ 'go': 'go-langserver'
      \ }
let g:lsc_auto_map = v:true

" CtrlP
let g:ctrlp_working_path_mode = 'raw'
let g:ctrlp_custom_ignore = {}
let g:ctrlp_custom_ignore.dir = '\v[\/](\.git|node_modules|build|__pycache__|.*\.egg-info)$'
let g:ctrlp_custom_ignore.file = '\v\.(pyc|pyo)$'

nnoremap <Leader>ff :<C-U>CtrlP<CR>
nnoremap <Leader>ft :<C-U>CtrlPTag<CR>
nnoremap <Leader>fb :<C-U>CtrlPBuffer<CR>

let home_wiki = {}
let home_wiki.path = '~/Dropbox/Notes/wiki/'
let home_wiki.syntax = 'markdown'
let home_wiki.ext = '.md'
let home_wiki.auto_export = 0

let g:vimwiki_list = [ home_wiki ]

let g:tagbar_type_vimwiki = {
      \ 'ctagstype' : 'markdown',
      \ 'kinds' : [ 'h:header', ],
      \ 'sort' : 0
      \ }
