if [ -f ~/.zshrc-local-pre ]; then
  . ~/.zshrc-local-pre
fi

fpath=(~/.dotfiles/zsh/fpath ~/.dotfiles/zsh/zsh-completions/src $fpath)

zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s

autoload -Uz compinit
if [[ $OSTYPE == "cygwin" ]]; then
  compinit -u
  # ignore security checks on compinit for cygwin, because cygwin
else
  compinit
fi
HISTFILE=~/.history
HISTSIZE=1000
SAVEHIST=1000
setopt incappendhistory sharehistory extendedhistory histallowclobber
setopt histignoredups histexpiredupsfirst histsavenodups histfindnodups
setopt notify noclobber promptsubst
unsetopt beep
bindkey -v
bindkey '^R' history-incremental-search-backward

export PAGER=less
export LESS='-m -R'
export EDITOR=vi
export VISUAL=$EDITOR

# aliases

alias ls='ls -bhF'
alias du='du -h'
alias df='df -h'

if (whence dircolors >& /dev/null); then
  eval `dircolors -b`
  zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
  alias ls='ls -bhF --color'
  alias rgrep='rgrep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
  alias grep='grep --color=auto'
fi

# functions

svndiff() {
  svn diff "${*}" | colordiff
}

fixssh() {
  for key in SSH_AUTH_SOCK SSH_CONNECTION SSH_CLIENT; do
    if (tmux show-environment | grep "^${key}" > /dev/null); then
      value=`tmux show-environment | grep "^${key}" | sed -e "s/^[A-Z_]*=//"`
      export ${key}="${value}"
    fi
  done
}

autoload -Uz colors && colors
autoload -Uz vcs_info

zstyle ':vcs_info:*' enable git svn

autoload -Uz promptinit && promptinit
prompt mike

xterm_title_precmd() {
  print -Pn "\e]0;%n@%M: %~\a"
}

if [[ -z $ZSH_NO_PRECMD ]]; then
  case $TERM in
    *xterm*)
      add-zsh-hook precmd xterm_title_precmd
  esac
fi

eval "$(tmuxifier init -)"

if (whence pipenv >& /dev/null); then
  eval $(pipenv --completion)
  export PIPENV_DEFAULT_PYTHON_VERSION="3.5"
  export PIPENV_SHELL_FANCY=True
  export PIPENV_VENV_IN_PROJECT=True
fi

if [ -f ~/.zshrc-local ]; then
  . ~/.zshrc-local
fi
